[package]
name = "aceeri-backend"
version = "0.1.0"
authors = ["Aceeri <conmcclusk@gmail.com>"]

[dependencies]
iron = "0.2.6"
staticfile = "0.1.0"
router = "0.1.0"
mount = { git = "https://github.com/iron/mount.git" }